local lib = require(game:GetService("ReplicatedStorage").Shared.Library)
local AFirework = require(game.ReplicatedStorage.Shared.Library["FireworkSystem copy"].AFirework)
local Botan = require(game.ReplicatedStorage.Shared.Library["FireworkSystem copy"].Botan)
local Gerb = require(game.ReplicatedStorage.Shared.Library["FireworkSystem copy"].Gerb)
local Kamuro = require(game.ReplicatedStorage.Shared.Library["FireworkSystem copy"].Kamuro)
local Kiku = require(game.ReplicatedStorage.Shared.Library["FireworkSystem copy"].Kiku)
local Ring = require(game.ReplicatedStorage.Shared.Library["FireworkSystem copy"].Ring)
local Toranoo = require(game.ReplicatedStorage.Shared.Library["FireworkSystem copy"].Toranoo)
local UFO = require(game.ReplicatedStorage.Shared.Library["FireworkSystem copy"].UFO)

-- local botan = Botan.new({Color1 = AFirework.Colors.K, Color2 = AFirework.Colors.Rb})
-- botan:launch()
-- botan:launchRandom()
-- botan:AutoSystem()

-- local new = Gerb.new({Parent = workspace.SpawnLocation})
-- task.wait(3)
-- new:launch()
-- task.wait(1)
-- new:launchRandom()
-- task.wait(1)
-- new:fan()
-- task.wait(1)
-- new:AutoSystem()

-- local Kamuro = Kamuro.new()
-- Kamuro:launch()
-- Kamuro:launchRandom()
-- Kamuro:AutoSystem()

-- local Kiku = Kiku.new({Color2 = AFirework.Colors.K, Color3 = AFirework.Colors.Sr})
-- Kiku:launch()
-- Kiku = Kiku.new()
-- Kiku:launch()
-- Kiku:launchRandom()
-- Kiku:AutoSystem()

-- local new = Ring.new()
-- new:launch()
-- new:launchRandom()
-- new:AutoSystem()


-- local new = Toranoo.new()
-- new:launch()
-- new:launchRandom()
-- new:fan()
-- new:AutoSystem()

-- local new = UFO.new()
-- new:launch()
-- new:launchRandom()
-- new:AutoSystem()
